// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var FibonacciLister=function(){
  var a=1;
  var b=2;
  var c=0;
  var array=[1,2];
  while(c<4000000){
    c=a+b;
    a=b;
    b=c;
    array.push(c);
  }
  return array;
}

var array= FibonacciLister();

var sum=0;
var i=0;

while(i<=array.length){
  if(array[i]%2===0){
    sum+=array[i];
  }
  i++;
}


console.log(sum);
